/** Quest 1 — Supply & Demand Basics */
module.exports = {
  key: 'q1',
  title: 'Supply & Demand Basics',
  description: 'Foundational ideas: markets, demand, supply, and equilibrium.',
  category: 'MICROECONOMICS',
  difficulty: 'BEGINNER',
  order_index: 1,
  xp_reward: 100,
  coin_reward: 25,
  icon_emoji: '📊',
  prerequisite_key: null,
  lessons: [
    {
      title: 'What is a Market?',
      content:
        "A market is any place where buyers and sellers come together to exchange goods and services. Markets can be online platforms, auction houses, or informal arrangements.\n\n**Buyers (demand)** want to purchase; **sellers (supply)** produce and offer goods. Their interaction sets prices and quantities.\n\nStudying markets helps us see how resources are allocated.",
      key_terms: [
        { term: 'Market', definition: 'Where buyers and sellers interact to exchange goods and services' },
        { term: 'Buyer', definition: 'Purchases goods or services' },
        { term: 'Seller', definition: 'Produces and offers goods for sale' },
        { term: 'Exchange', definition: 'Trading goods, services, or money between parties' },
      ],
      fun_fact: 'The New York Stock Exchange processes over 1.5 billion shares every day.',
      real_world_example: 'Amazon connects millions of buyers with sellers worldwide.',
    },
    {
      title: 'The Law of Demand',
      content:
        'The **Law of Demand**: when price rises, quantity demanded falls (other things equal). This makes a downward-sloping **demand curve**.\n\n**Substitution effect:** consumers switch to alternatives when price rises.\n\n**Income effect:** higher prices reduce purchasing power. Tastes, income, related goods, and expectations can shift the whole curve.',
      key_terms: [
        { term: 'Law of Demand', definition: 'Price up → quantity demanded down (ceteris paribus)' },
        { term: 'Demand Curve', definition: 'Shows the inverse price–quantity relationship' },
        { term: 'Quantity Demanded', definition: 'Amount people buy at a specific price' },
        { term: 'Substitution Effect', definition: 'Switching to cheaper alternatives when price rises' },
        { term: 'Income Effect', definition: 'Price changes affect real income' },
      ],
      fun_fact: 'Black Friday sales can spike electronics demand simply because prices drop.',
      real_world_example: 'Higher gas prices lead people to drive less or carpool — classic demand.',
    },
    {
      title: 'The Law of Supply',
      content:
        'The **Law of Supply**: when price rises, quantity supplied rises (ceteris paribus). The **supply curve** slopes upward.\n\nHigher prices mean higher potential profits. Costs, technology, sellers, regulation, and expectations **shift** supply.',
      key_terms: [
        { term: 'Law of Supply', definition: 'Price up → quantity supplied up (ceteris paribus)' },
        { term: 'Supply Curve', definition: 'Shows the direct price–quantity supplied relationship' },
        { term: 'Quantity Supplied', definition: 'Amount producers sell at a specific price' },
        { term: 'Input Costs', definition: 'Costs of labor, materials, and overhead' },
      ],
      fun_fact: 'A modern car factory can produce over 1,000 vehicles per day with better technology.',
      real_world_example: 'Higher coffee bean prices encourage farmers to plant more coffee.',
    },
    {
      title: 'Market Equilibrium',
      content:
        '**Equilibrium** is where supply and demand cross: quantity demanded equals quantity supplied.\n\n**Surplus:** price above equilibrium → excess supply pushes price down.\n\n**Shortage:** price below equilibrium → excess demand pushes price up.\n\nAdam Smith called the self-regulating process the **Invisible Hand**.',
      key_terms: [
        { term: 'Equilibrium', definition: 'No tendency for price to change; quantities match' },
        { term: 'Equilibrium Price', definition: 'Price that clears the market' },
        { term: 'Surplus', definition: 'Quantity supplied exceeds quantity demanded' },
        { term: 'Shortage', definition: 'Quantity demanded exceeds quantity supplied' },
        { term: 'Invisible Hand', definition: 'Markets self-regulate through incentives' },
      ],
      fun_fact: "Adam Smith published *The Wealth of Nations* in 1776.",
      real_world_example: 'Mask and sanitizer shortages in 2020 illustrated huge demand vs limited supply.',
    },
  ],
  challenges: [
    {
      type: 'MULTIPLE_CHOICE',
      question:
        'According to the Law of Demand, when the price of a good increases, what happens to the quantity demanded?',
      options: ['It increases', 'It decreases', 'It stays the same', 'It becomes unpredictable'],
      correct_answer: 'It decreases',
      explanation:
        'Demand slopes down: higher prices reduce quantity demanded as goods feel less affordable.',
      hint: 'Think about your favorite snack getting pricier.',
      difficulty: 'BEGINNER',
      time_limit: 30,
      xp_reward: 10,
    },
    {
      type: 'TRUE_FALSE',
      question: 'A supply curve slopes downward from left to right.',
      options: ['True', 'False'],
      correct_answer: 'False',
      explanation: 'Supply slopes **upward**. Demand slopes downward.',
      difficulty: 'BEGINNER',
      time_limit: 20,
      xp_reward: 10,
    },
    {
      type: 'FILL_BLANK',
      question: 'The point where the supply curve meets the demand curve is called market ______.',
      options: null,
      correct_answer: 'equilibrium',
      explanation: 'Equilibrium is where the market clears.',
      difficulty: 'BEGINNER',
      time_limit: 30,
      xp_reward: 10,
    },
    {
      type: 'MULTIPLE_CHOICE',
      question: 'If there is a SURPLUS in the market, what does that mean?',
      options: [
        'Demand exceeds supply',
        'Supply exceeds demand',
        'The market is in equilibrium',
        'Prices are too low',
      ],
      correct_answer: 'Supply exceeds demand',
      explanation: 'Surplus means unsold inventory at a price above equilibrium.',
      difficulty: 'BEGINNER',
      time_limit: 30,
      xp_reward: 10,
    },
    {
      type: 'MULTIPLE_CHOICE',
      question:
        'Which of the following would shift the demand curve for umbrellas to the RIGHT (increase demand)?',
      options: [
        'A decrease in the price of umbrellas',
        'Weather forecasts predicting more rain',
        'An increase in the cost of making umbrellas',
        'A new tax on umbrellas',
      ],
      correct_answer: 'Weather forecasts predicting more rain',
      explanation: 'A shift is a change in desire at every price—not a movement along the curve.',
      difficulty: 'BEGINNER',
      time_limit: 30,
      xp_reward: 15,
    },
    {
      type: 'SCENARIO',
      question:
        "A severe frost destroys 40% of Florida's orange crop. What is the most likely effect on the market for orange juice?",
      options: [
        'Price falls, quantity rises',
        'Price rises, quantity falls',
        'Price falls, quantity falls',
        'Price rises, quantity rises',
      ],
      correct_answer: 'Price rises, quantity falls',
      explanation: 'Supply shifts left: higher prices and lower quantity—a supply shock.',
      difficulty: 'BEGINNER',
      time_limit: 45,
      xp_reward: 15,
    },
    {
      type: 'MULTIPLE_CHOICE',
      question: "What does the 'Invisible Hand' refer to in economics?",
      options: [
        'Government regulation of markets',
        'The self-regulating nature of free markets',
        'Hidden taxes on goods',
        'Secret business agreements',
      ],
      correct_answer: 'The self-regulating nature of free markets',
      explanation: 'Smith argued decentralized choices can guide resources without central planning.',
      difficulty: 'BEGINNER',
      time_limit: 30,
      xp_reward: 10,
    },
    {
      type: 'TRUE_FALSE',
      question: 'When the price of a product is below the equilibrium price, a shortage occurs.',
      options: ['True', 'False'],
      correct_answer: 'True',
      explanation: 'Low prices mean more buyers than sellers want to serve → shortage.',
      difficulty: 'BEGINNER',
      time_limit: 20,
      xp_reward: 10,
    },
  ],
};
