/** Quest 2 — GDP & Economic Growth */
module.exports = {
  key: 'q2',
  title: 'GDP & Economic Growth',
  description: 'Measure output: GDP components, real vs nominal, and growth.',
  category: 'MACROECONOMICS',
  difficulty: 'BEGINNER',
  order_index: 2,
  xp_reward: 100,
  coin_reward: 25,
  icon_emoji: '🏛️',
  prerequisite_key: 'q1',
  lessons: [
    {
      title: 'What is GDP?',
      content:
        '**GDP** is the total value of finished goods and services produced inside a country in a period. It is the economy’s “report card.”\n\nGDP includes new production; it excludes used goods, illegal activity, unpaid home production, and intermediate goods counted elsewhere.',
      key_terms: [
        { term: 'GDP', definition: 'Total value of finished output produced domestically in a period' },
        { term: 'Economic Output', definition: 'Quantity of goods and services produced' },
        { term: 'Finished Goods', definition: 'Products ready for sale to end users' },
        { term: 'Intermediate Goods', definition: 'Inputs not counted separately when output is counted' },
      ],
      fun_fact: 'US GDP exceeds $25 trillion — huge output per person.',
      real_world_example: 'News “economy grew 2.5%” usually means real GDP growth.',
    },
    {
      title: 'Components of GDP',
      content:
        '**GDP = C + I + G + (X − M)**\n\n**C** consumption (~70% US), **I** investment in equipment & structures (**not** stocks), **G** government purchases (not transfers), **NX** net exports (exports minus imports).',
      key_terms: [
        { term: 'Consumer Spending (C)', definition: 'Household purchases of goods and services' },
        { term: 'Investment (I)', definition: 'Business capital spending and residential construction' },
        { term: 'Government Spending (G)', definition: 'Government purchases of goods/services' },
        { term: 'Net Exports (NX)', definition: 'Exports minus imports' },
        { term: 'Trade Deficit', definition: 'Imports exceed exports' },
      ],
      fun_fact: 'Consumer spending is the largest GDP slice in the US.',
      real_world_example: 'Holiday shopping can lift Q4 GDP.',
    },
    {
      title: 'Nominal vs. Real GDP',
      content:
        '**Nominal GDP** uses current prices and can rise with inflation alone.\n\n**Real GDP** uses constant base-year prices to show true growth.\n\nReal ≈ nominal growth minus inflation (simple intuition).',
      key_terms: [
        { term: 'Nominal GDP', definition: 'GDP at current prices' },
        { term: 'Real GDP', definition: 'GDP adjusted for inflation' },
        { term: 'GDP Deflator', definition: 'Price index linking nominal to real GDP' },
        { term: 'Base Year', definition: 'Reference prices for real GDP' },
      ],
      fun_fact: 'Nominal figures can look “strong” during hyperinflation when real output falls.',
      real_world_example: 'Headline growth reports emphasize real GDP.',
    },
    {
      title: 'Economic Growth',
      content:
        '**Growth** is rising real GDP over time. Drivers include labor, capital, **technology**, education, and resources.\n\nThe **business cycle** moves through expansion, peak, recession (two quarters of falling real GDP), trough, and recovery.',
      key_terms: [
        { term: 'Economic Growth', definition: 'Sustained increase in real GDP' },
        { term: 'GDP Growth Rate', definition: 'Percent change in real GDP' },
        { term: 'Recession', definition: 'Two consecutive quarters of falling real GDP (rule of thumb)' },
        { term: 'Business Cycle', definition: 'Fluctuations between expansion and contraction' },
        { term: 'Expansion', definition: 'GDP rising, unemployment often falling' },
      ],
      fun_fact: 'China averaged ~10% yearly growth for decades.',
      real_world_example: 'COVID caused a sharp contraction then a fast rebound in US GDP.',
    },
  ],
  challenges: [
    {
      type: 'MULTIPLE_CHOICE',
      question: 'What does GDP stand for?',
      options: [
        'Gross Domestic Product',
        'General Domestic Price',
        'Gross Demand Percentage',
        'Global Development Plan',
      ],
      correct_answer: 'Gross Domestic Product',
      explanation: 'GDP counts finished output produced within borders.',
      difficulty: 'BEGINNER',
      time_limit: 20,
      xp_reward: 10,
    },
    {
      type: 'MULTIPLE_CHOICE',
      question: 'Which component makes up the largest share of US GDP?',
      options: ['Government Spending (G)', 'Investment (I)', 'Consumer Spending (C)', 'Net Exports (NX)'],
      correct_answer: 'Consumer Spending (C)',
      explanation: 'Household consumption is the dominant share.',
      difficulty: 'BEGINNER',
      time_limit: 30,
      xp_reward: 10,
    },
    {
      type: 'FILL_BLANK',
      question: 'The GDP formula is: GDP = C + I + G + ___.',
      options: null,
      correct_answer: 'NX',
      explanation: 'NX is exports minus imports.',
      difficulty: 'BEGINNER',
      time_limit: 30,
      xp_reward: 10,
    },
    {
      type: 'TRUE_FALSE',
      question: 'Real GDP is adjusted for inflation, while Nominal GDP is not.',
      options: ['True', 'False'],
      correct_answer: 'True',
      explanation: 'Real GDP removes price-level changes.',
      difficulty: 'BEGINNER',
      time_limit: 20,
      xp_reward: 10,
    },
    {
      type: 'MULTIPLE_CHOICE',
      question: 'A recession is officially defined as:',
      options: [
        'One quarter of negative GDP growth',
        'Two consecutive quarters of declining Real GDP',
        'Any year where unemployment rises',
        'A stock market crash of more than 20%',
      ],
      correct_answer: 'Two consecutive quarters of declining Real GDP',
      explanation: 'Common rule of thumb used in textbooks and media.',
      difficulty: 'BEGINNER',
      time_limit: 30,
      xp_reward: 15,
    },
    {
      type: 'SCENARIO',
      question:
        "If a country's Nominal GDP increased by 8% this year, but inflation was 5%, what was the approximate Real GDP growth?",
      options: ['8%', '5%', '3%', '13%'],
      correct_answer: '3%',
      explanation: 'Approximate real growth ≈ nominal − inflation.',
      difficulty: 'BEGINNER',
      time_limit: 45,
      xp_reward: 15,
    },
    {
      type: 'MULTIPLE_CHOICE',
      question: 'Which of the following is NOT counted in GDP?',
      options: [
        'A new car sold at a dealership',
        'A haircut from a barber',
        'A used textbook sold on eBay',
        'A house built this year',
      ],
      correct_answer: 'A used textbook sold on eBay',
      explanation: 'Used goods were counted when first sold—resale avoids double counting.',
      difficulty: 'BEGINNER',
      time_limit: 30,
      xp_reward: 10,
    },
    {
      type: 'MULTIPLE_CHOICE',
      question: 'Which is the most important driver of LONG-TERM economic growth?',
      options: [
        'Increasing the number of workers',
        'Technological advancement',
        'Finding more natural resources',
        'Government spending',
      ],
      correct_answer: 'Technological advancement',
      explanation: 'Technology raises productivity and living standards over decades.',
      difficulty: 'BEGINNER',
      time_limit: 30,
      xp_reward: 15,
    },
  ],
};
