/** Quest 3 — Budgeting 101 */
module.exports = {
  key: 'q3',
  title: 'Budgeting 101',
  description: 'Income, expenses, rules of thumb, emergency funds, and tracking.',
  category: 'PERSONAL_FINANCE',
  difficulty: 'BEGINNER',
  order_index: 3,
  xp_reward: 100,
  coin_reward: 25,
  icon_emoji: '💰',
  prerequisite_key: null,
  lessons: [
    {
      title: 'Income & Expenses',
      content:
        '**Income** can be earned, passive, or other. **Gross income** is before tax; **net income** is take-home.\n\n**Fixed** expenses repeat (rent); **variable** expenses change (groceries). Rule: spend less than you earn to build surplus.',
      key_terms: [
        { term: 'Gross Income', definition: 'Total income before deductions' },
        { term: 'Net Income', definition: 'Take-home pay after taxes' },
        { term: 'Fixed Expenses', definition: 'Stable costs like rent' },
        { term: 'Variable Expenses', definition: 'Fluctuating costs like dining' },
      ],
      fun_fact: 'Many households spend nearly all annual income—small savings margins are common.',
      real_world_example: 'A $50k salary may net ~$38k after taxes and payroll deductions.',
    },
    {
      title: 'The 50/30/20 Rule',
      content:
        '**50% needs**, **30% wants**, **20% savings/debt payoff** on take-home pay.\n\nNeeds: housing, utilities, basics. Wants: dining out, hobbies. Savings: emergency fund, retirement, extra debt payments.',
      key_terms: [
        { term: '50/30/20 Rule', definition: 'Simple split for needs, wants, savings' },
        { term: 'Needs', definition: 'Essentials required to function' },
        { term: 'Wants', definition: 'Non-essential quality-of-life spending' },
        { term: 'Budget', definition: 'Plan for allocating income' },
      ],
      fun_fact: 'Budgeters often report less money stress.',
      real_world_example: '$3,000 take-home → ~$1,500 needs, $900 wants, $600 savings.',
    },
    {
      title: 'Emergency Funds',
      content:
        'Save for **true emergencies**: job loss, repairs, medical bills. Target **3–6 months** of expenses in a **liquid, safe** account—not volatile investments.',
      key_terms: [
        { term: 'Emergency Fund', definition: 'Cash buffer for unexpected costs' },
        { term: 'Liquid Asset', definition: 'Easily accessible cash or equivalents' },
        { term: 'High-Yield Savings', definition: 'Savings account with better rates' },
        { term: 'Safety Net', definition: 'Resources that prevent debt spirals' },
      ],
      fun_fact: 'Many adults cannot cover an unexpected $1,000 bill.',
      real_world_example: 'COVID job losses showed who had months of expenses saved.',
    },
    {
      title: 'Tracking Your Spending',
      content:
        'Measure to improve: apps, spreadsheets, or **envelope** cash methods reveal leaks like forgotten subscriptions or frequent small purchases.',
      key_terms: [
        { term: 'Spending Tracking', definition: 'Recording expenses by category' },
        { term: 'Envelope System', definition: 'Cash buckets per category' },
        { term: 'Spending Leak', definition: 'Small recurring costs that add up' },
      ],
      fun_fact: 'Daily $5 items can cost thousands yearly.',
      real_world_example: 'People often underestimate dining-out totals until they track.',
    },
  ],
  challenges: [
    {
      type: 'MULTIPLE_CHOICE',
      question: 'According to the 50/30/20 rule, what percentage should go toward SAVINGS and debt repayment?',
      options: ['50%', '30%', '20%', '10%'],
      correct_answer: '20%',
      explanation: '20% builds long-term security.',
      difficulty: 'BEGINNER',
      time_limit: 20,
      xp_reward: 10,
    },
    {
      type: 'TRUE_FALSE',
      question: 'Your gross income is the amount you actually take home after taxes.',
      options: ['True', 'False'],
      correct_answer: 'False',
      explanation: 'Gross is before taxes; net is take-home.',
      difficulty: 'BEGINNER',
      time_limit: 20,
      xp_reward: 10,
    },
    {
      type: 'FILL_BLANK',
      question: 'Financial experts recommend having ___ to ___ months of living expenses in an emergency fund.',
      options: null,
      correct_answer: '3 to 6',
      explanation: 'A common rule of thumb is 3–6 months of expenses.',
      difficulty: 'BEGINNER',
      time_limit: 30,
      xp_reward: 10,
    },
    {
      type: 'MULTIPLE_CHOICE',
      question: 'Which of the following is a FIXED expense?',
      options: ['Groceries', 'Monthly rent', 'Dining out', 'Clothing shopping'],
      correct_answer: 'Monthly rent',
      explanation: 'Rent is predictable month to month.',
      difficulty: 'BEGINNER',
      time_limit: 25,
      xp_reward: 10,
    },
    {
      type: 'SCENARIO',
      question:
        'You earn $4,000/month after taxes. Using the 50/30/20 rule, how much should you allocate to WANTS (non-essential spending)?',
      options: ['$800', '$1,200', '$2,000', '$1,500'],
      correct_answer: '$1,200',
      explanation: '30% of $4,000 = $1,200.',
      difficulty: 'BEGINNER',
      time_limit: 30,
      xp_reward: 15,
    },
    {
      type: 'MULTIPLE_CHOICE',
      question: 'Where should you keep your emergency fund?',
      options: [
        'In the stock market for growth',
        'In a high-yield savings account',
        'Under your mattress',
        'In cryptocurrency',
      ],
      correct_answer: 'In a high-yield savings account',
      explanation: 'Safety and liquidity matter most for emergencies.',
      difficulty: 'BEGINNER',
      time_limit: 30,
      xp_reward: 10,
    },
    {
      type: 'TRUE_FALSE',
      question: 'If you spend $5 on coffee every workday, that adds up to about $1,300 per year.',
      options: ['True', 'False'],
      correct_answer: 'True',
      explanation: '$5 × 5 days × 52 weeks ≈ $1,300.',
      difficulty: 'BEGINNER',
      time_limit: 25,
      xp_reward: 10,
    },
    {
      type: 'MULTIPLE_CHOICE',
      question: 'What is the FIRST step to improving your financial health?',
      options: [
        'Investing in stocks',
        'Tracking your spending',
        'Getting a higher-paying job',
        'Cutting all non-essential expenses',
      ],
      correct_answer: 'Tracking your spending',
      explanation: 'You can’t improve what you don’t measure.',
      difficulty: 'BEGINNER',
      time_limit: 30,
      xp_reward: 10,
    },
  ],
};
