/** Quest 4 — Elasticity */
module.exports = {
  key: 'q4',
  title: 'Elasticity',
  description: 'Price elasticity, revenue, and related elasticities.',
  category: 'MICROECONOMICS',
  difficulty: 'INTERMEDIATE',
  order_index: 4,
  xp_reward: 150,
  coin_reward: 35,
  icon_emoji: '📏',
  prerequisite_key: 'q1',
  lessons: [
    {
      title: 'What is Price Elasticity?',
      content:
        '**PED** measures how sensitive quantity demanded is to price: (%ΔQd)/(%ΔP). |PED|>1 **elastic**; <|1| **inelastic**; =1 unit elastic.\n\nElasticity guides pricing and tax incidence.',
      key_terms: [
        { term: 'PED', definition: '% change in quantity demanded over % change in price' },
        { term: 'Elastic Demand', definition: 'Quantity responds strongly to price' },
        { term: 'Inelastic Demand', definition: 'Quantity responds weakly to price' },
        { term: 'Unit Elastic', definition: 'Equal % response' },
      ],
      fun_fact: 'Insulin demand is highly inelastic—big ethical debates about pricing.',
      real_world_example: 'Streaming price hikes changed cancellations as demand became more elastic.',
    },
    {
      title: 'Elastic vs. Inelastic Goods',
      content:
        '**Elastic:** luxuries, many substitutes, large budget share.\n\n**Inelastic:** necessities, few substitutes, small budget share.\n\nMore substitutes → more elastic over time.',
      key_terms: [
        { term: 'Substitute Good', definition: 'Alternative that satisfies same need' },
        { term: 'Necessity', definition: 'Good needed for basic living' },
        { term: 'Luxury Good', definition: 'Non-essential good' },
        { term: 'Time Horizon', definition: 'Longer horizons often mean more elastic demand' },
      ],
      fun_fact: 'Salt spending is tiny as a budget share—very inelastic.',
      real_world_example: 'Short-run gasoline demand is inelastic; long-run more elastic.',
    },
    {
      title: 'Elasticity and Total Revenue',
      content:
        '**TR = P × Q**. If demand is **elastic**, raising price lowers TR. If **inelastic**, raising price raises TR. Unit elastic maximizes TR in simple cases.',
      key_terms: [
        { term: 'Total Revenue', definition: 'Price times quantity sold' },
        { term: 'Revenue Maximization', definition: 'Price where TR peaks (unit elastic intuition)' },
        { term: 'Pricing Strategy', definition: 'Prices based on elasticity' },
      ],
      fun_fact: 'Airlines charge business travelers far more than leisure travelers.',
      real_world_example: 'Happy hour lowers drink prices when demand is elastic among casual patrons.',
    },
    {
      title: 'Other Types of Elasticity',
      content:
        '**Income elasticity (YED):** normal vs inferior goods.\n\n**Cross-price (XED):** substitutes (+) vs complements (−).\n\n**Supply elasticity:** how quantity supplied responds to price.',
      key_terms: [
        { term: 'Income Elasticity', definition: 'Response of demand to income changes' },
        { term: 'Cross-Price Elasticity', definition: 'Response of good A to price of good B' },
        { term: 'Normal Good', definition: 'Demand rises with income' },
        { term: 'Inferior Good', definition: 'Demand falls as income rises' },
        { term: 'Complements', definition: 'Consumed together; cross-price negative' },
      ],
      fun_fact: 'Ramen noodles are a classic inferior good for many students.',
      real_world_example: 'iPhone vs Samsung phones are substitutes; phones and cases are complements.',
    },
  ],
  challenges: [
    {
      type: 'MULTIPLE_CHOICE',
      question: 'If a 10% increase in price causes a 20% decrease in quantity demanded, the demand is:',
      options: ['Elastic', 'Inelastic', 'Unit elastic', 'Perfectly inelastic'],
      correct_answer: 'Elastic',
      explanation: '|PED| = 20/10 = 2 > 1 → elastic.',
      difficulty: 'INTERMEDIATE',
      time_limit: 30,
      xp_reward: 15,
    },
    {
      type: 'TRUE_FALSE',
      question: 'If demand is inelastic, raising the price will increase total revenue.',
      options: ['True', 'False'],
      correct_answer: 'True',
      explanation: 'Quantity falls proportionally less than price rises.',
      difficulty: 'INTERMEDIATE',
      time_limit: 25,
      xp_reward: 15,
    },
    {
      type: 'FILL_BLANK',
      question: 'Goods with many available substitutes tend to have __________ demand.',
      options: null,
      correct_answer: 'elastic',
      explanation: 'Easy switching makes quantity responsive to price.',
      difficulty: 'INTERMEDIATE',
      time_limit: 30,
      xp_reward: 15,
    },
    {
      type: 'SCENARIO',
      question:
        'Gasoline prices increase by 15%, and quantity demanded only drops by 3%. What is the price elasticity of demand?',
      options: ['5.0 (elastic)', '0.2 (inelastic)', '1.0 (unit elastic)', '0.5 (inelastic)'],
      correct_answer: '0.2 (inelastic)',
      explanation: '3/15 = 0.2—very inelastic in the short run.',
      difficulty: 'INTERMEDIATE',
      time_limit: 45,
      xp_reward: 20,
    },
    {
      type: 'MULTIPLE_CHOICE',
      question: 'Which of the following is most likely an INFERIOR good?',
      options: [
        'Brand-name clothing',
        'Organic produce',
        'Instant ramen noodles',
        'Electric vehicles',
      ],
      correct_answer: 'Instant ramen noodles',
      explanation: 'Demand falls as consumers can afford better meals.',
      difficulty: 'INTERMEDIATE',
      time_limit: 30,
      xp_reward: 15,
    },
    {
      type: 'MULTIPLE_CHOICE',
      question: "If Coca-Cola's price rises and Pepsi's demand increases, these products are:",
      options: ['Complementary goods', 'Substitute goods', 'Inferior goods', 'Unrelated goods'],
      correct_answer: 'Substitute goods',
      explanation: 'Positive cross-price relationship.',
      difficulty: 'INTERMEDIATE',
      time_limit: 25,
      xp_reward: 15,
    },
    {
      type: 'SCENARIO',
      question:
        'A concert venue sells 500 tickets at $50 each. They consider raising to $60. If demand elasticity is 0.5, should they raise the price to maximize revenue?',
      options: [
        'Yes — revenue will increase because demand is inelastic',
        'No — revenue will decrease because demand is elastic',
        'It doesn’t matter — revenue stays the same',
        'Need more information to decide',
      ],
      correct_answer: 'Yes — revenue will increase because demand is inelastic',
      explanation: 'With inelastic demand, price increases dominate the quantity drop.',
      difficulty: 'INTERMEDIATE',
      time_limit: 45,
      xp_reward: 20,
    },
    {
      type: 'TRUE_FALSE',
      question: 'Over time, demand for most products tends to become MORE elastic.',
      options: ['True', 'False'],
      correct_answer: 'True',
      explanation: 'Consumers find substitutes and adjust habits over longer horizons.',
      difficulty: 'INTERMEDIATE',
      time_limit: 25,
      xp_reward: 15,
    },
  ],
};
