/** Quest 5 — Inflation & Deflation */
module.exports = {
  key: 'q5',
  title: 'Inflation & Deflation',
  description: 'CPI, causes, winners/losers, and policy responses.',
  category: 'MACROECONOMICS',
  difficulty: 'INTERMEDIATE',
  order_index: 5,
  xp_reward: 150,
  coin_reward: 35,
  icon_emoji: '📈',
  prerequisite_key: 'q2',
  lessons: [
    {
      title: 'What is Inflation?',
      content:
        '**Inflation** is a sustained rise in the general price level—money buys less.\n\n**CPI** tracks a typical basket. Mild inflation (~2%) is common; hyperinflation is destructive.',
      key_terms: [
        { term: 'Inflation', definition: 'Ongoing increase in average prices' },
        { term: 'CPI', definition: 'Consumer price index measuring basket inflation' },
        { term: 'Purchasing Power', definition: 'What a currency can buy' },
        { term: 'Deflation', definition: 'Sustained decrease in average prices' },
      ],
      fun_fact: 'Ticket prices illustrate long-run inflation vividly.',
      real_world_example: 'Fed targets ~2% inflation for flexibility in downturns.',
    },
    {
      title: 'Causes of Inflation',
      content:
        '**Demand-pull:** spending outruns production.\n\n**Cost-push:** higher costs raise prices.\n\n**Built-in:** wage–price spirals. **Money supply** growth can also raise prices if output lags.',
      key_terms: [
        { term: 'Demand-Pull Inflation', definition: 'Too much demand relative to supply' },
        { term: 'Cost-Push Inflation', definition: 'Higher costs passed to consumers' },
        { term: 'Wage-Price Spiral', definition: 'Wages and prices chase each other up' },
        { term: 'Money Supply', definition: 'Total money circulating' },
      ],
      fun_fact: 'Extreme money printing can create hyperinflation episodes.',
      real_world_example: '2021–22 combined demand recovery with supply constraints.',
    },
    {
      title: 'Effects of Inflation',
      content:
        'Hurt: savers on fixed nominal returns, fixed incomes if not indexed.\n\nHelp: borrowers repaying in cheaper dollars, some asset owners.\n\n**Real interest rate** ≈ nominal rate − inflation.',
      key_terms: [
        { term: 'Real Wage', definition: 'Wage adjusted for inflation' },
        { term: 'Nominal Value', definition: 'Face value not adjusted for prices' },
        { term: 'Real Interest Rate', definition: 'Nominal rate minus inflation' },
        { term: 'Hyperinflation', definition: 'Extremely rapid price increases' },
      ],
      fun_fact: 'Weimar Germany saw prices double in days.',
      real_world_example: 'If inflation exceeds savings interest, purchasing power falls.',
    },
    {
      title: 'Fighting Inflation',
      content:
        'Central banks **raise rates** and tighten liquidity; governments may cut spending or raise taxes. Short-run **Phillips curve** trade-offs exist between inflation and unemployment.',
      key_terms: [
        { term: 'Monetary Policy', definition: 'Central bank tools affecting money and rates' },
        { term: 'Interest Rate', definition: 'Cost of borrowing / return on saving' },
        { term: 'Fiscal Policy', definition: 'Government spending and tax choices' },
        { term: 'Phillips Curve', definition: 'Short-run inflation–unemployment trade-off' },
        { term: 'Inflation Targeting', definition: 'Public inflation goal for policy' },
      ],
      fun_fact: 'The Fed hiked aggressively in 2022–23 to reduce inflation.',
      real_world_example: 'Tighter credit slows spending and cools prices.',
    },
  ],
  challenges: [
    {
      type: 'MULTIPLE_CHOICE',
      question: 'What does the Consumer Price Index (CPI) measure?',
      options: [
        'Stock market performance',
        'Average price changes of consumer goods and services',
        'GDP growth rate',
        'Government spending levels',
      ],
      correct_answer: 'Average price changes of consumer goods and services',
      explanation: 'CPI tracks a household consumption basket.',
      difficulty: 'INTERMEDIATE',
      time_limit: 25,
      xp_reward: 15,
    },
    {
      type: 'TRUE_FALSE',
      question: 'Borrowers generally benefit from unexpected inflation.',
      options: ['True', 'False'],
      correct_answer: 'True',
      explanation: 'Repayment uses money with lower real value.',
      difficulty: 'INTERMEDIATE',
      time_limit: 20,
      xp_reward: 15,
    },
    {
      type: 'FILL_BLANK',
      question:
        'The Real Interest Rate equals the Nominal Interest Rate minus the __________ rate.',
      options: null,
      correct_answer: 'inflation',
      explanation: 'Fisher-style decomposition (simple form).',
      difficulty: 'INTERMEDIATE',
      time_limit: 30,
      xp_reward: 15,
    },
    {
      type: 'SCENARIO',
      question:
        'Your savings account pays 4% interest annually. If inflation is 6%, what is happening to the purchasing power of your savings?',
      options: [
        "It's growing by 4%",
        "It's growing by 2%",
        "It's shrinking by 2%",
        'It stays the same',
      ],
      correct_answer: "It's shrinking by 2%",
      explanation: 'Real return ≈ 4% − 6%.',
      difficulty: 'INTERMEDIATE',
      time_limit: 30,
      xp_reward: 20,
    },
    {
      type: 'MULTIPLE_CHOICE',
      question: 'Which type of inflation is described as “too much money chasing too few goods”?',
      options: [
        'Cost-push inflation',
        'Demand-pull inflation',
        'Built-in inflation',
        'Hyperinflation',
      ],
      correct_answer: 'Demand-pull inflation',
      explanation: 'Aggregate demand exceeds productive capacity.',
      difficulty: 'INTERMEDIATE',
      time_limit: 25,
      xp_reward: 15,
    },
    {
      type: 'MULTIPLE_CHOICE',
      question: "What is the Federal Reserve's primary tool for fighting inflation?",
      options: [
        'Printing more money',
        'Raising interest rates',
        'Lowering taxes',
        'Increasing government spending',
      ],
      correct_answer: 'Raising interest rates',
      explanation: 'Tighter financial conditions cool demand.',
      difficulty: 'INTERMEDIATE',
      time_limit: 25,
      xp_reward: 15,
    },
    {
      type: 'SCENARIO',
      question:
        'Oil prices suddenly spike due to a conflict in the Middle East. This causes prices to rise across the economy. What type of inflation is this?',
      options: [
        'Demand-pull inflation',
        'Cost-push inflation',
        'Built-in inflation',
        'Monetary inflation',
      ],
      correct_answer: 'Cost-push inflation',
      explanation: 'Higher energy costs raise production and transport costs broadly.',
      difficulty: 'INTERMEDIATE',
      time_limit: 30,
      xp_reward: 20,
    },
    {
      type: 'TRUE_FALSE',
      question: 'Most modern central banks target an inflation rate of 0%.',
      options: ['True', 'False'],
      correct_answer: 'False',
      explanation: 'Many target ~2% for stability and policy space.',
      difficulty: 'INTERMEDIATE',
      time_limit: 20,
      xp_reward: 15,
    },
  ],
};
